<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamic Web Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        #dynamicContent {
            color: #333;
            font-size: 18px;
        }
    </style>
</head>
<body>

<h1>Welcome to the Dynamic Web Page!</h1>

<p id="dynamicContent">Loading dynamic content...</p>

<button onclick="updateContent()">Update Content</button>

<script>
    function updateContent() {
        var dynamicContentElement = document.getElementById("dynamicContent");

        var randomNumber = Math.floor(Math.random() * 100) + 1;
        dynamicContentElement.textContent = "New Dynamic Content: " + randomNumber;
    }
</script>

<?php
if (!isset($_GET['action'])) {
    $randomNumber = rand(1, 100);
    echo "<script>document.getElementById('dynamicContent').textContent = 'Dynamic content generated by PHP: $randomNumber';</script>";
}
?>

</body>
</html>
